### ISSUE TITLE
How to get sender address in handle(...)

### ISSUE THREAD

**Issue by superlou** [fafhrd91/actix#12]
Continuing the conversation from #9, my last stumbling block was how to get the `Address` and `SyncAddress` of the sender in a `handle(...)`.  I believe it should be accessible from the `ctx`, but is there an example of this?

**Comment by superlou** [comment]
I ended up doing the first (sending the sender address with the message).  I only thought it might be possible from the [Wikipedia Actor Model page](https://en.wikipedia.org/wiki/Actor_model) which says the following:

> Recipients of messages are identified by address, sometimes called "mailing address". Thus an actor can only communicate with actors whose addresses it has. It can obtain those from a message it receives, or if the address is for an actor it has itself created.

I mistook the idea "obtain those from a message it receives" as it was some inherent property of a message, as opposed to data sent in the message.  I also understand that this framework may address some concepts differently than the standard actor model.

I thought I needed bidirectional communications since in my application, Bot actors send data they receive from the user to the Engine actor, and the Engine actor needs to send text for the Bot actors to send to the user.  I think I might have been able to get away with something similar without a full actor system by giving each Bot a send channel, and letting the Engine receive from all the Bots it's created in a `std::sync::mpsc::recv(...)` loop.  Then I could let the Engine look up the Bots from a vector and directly call methods on them.  At the time, Actors sounded more elegant. :)

**Comment by fafhrd91** [comment]
Bot can send `Connect` or `Subscribe` message to Engine, then it is easy.
I use this approach in chat example https://github.com/fafhrd91/actix/blob/master/examples/chat/src/server.rs#L15

Or Engine could use `Subscriber<SendMessage>`, then it can send messages to any actor that can handle `SendMessage`
this approach I use in signal actor, https://github.com/fafhrd91/actix/blob/master/src/actors/signal.rs#L186

**Comment by fafhrd91** [comment]
I am not sure if it is possible to express Sender address in type safe way is possible without complicating trait definitions

**Comment by superlou** [comment]
Both of those techniques sound reasonable.  I have some application logic to sort out, then will give the Connect/Subscribe message technique a try.  For now, sending the Engine address with the CreateBot message is working.  Thanks!

**Comment by fafhrd91** [comment]
added new arbiter's method https://fafhrd91.github.io/actix/actix/struct.Arbiter.html#method.start

**Comment by superlou** [comment]
I'm probably being dense, but how does that method help?

**Comment by fafhrd91** [comment]
you can start new actor in separate event loop and get sync address immediately
